# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-24 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import ferienhausWeb.models


class Migration(migrations.Migration):

    dependencies = [
        ('ferienhausWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('picture', models.FileField(blank=True, null=True, upload_to=ferienhausWeb.models.get_image_path)),
            ],
        ),
    ]
