# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 11:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferienhausWeb', '0004_auto_20161210_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
