# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import ferienhausWeb.models


class Migration(migrations.Migration):

    dependencies = [
        ('ferienhausWeb', '0006_auto_20161220_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=ferienhausWeb.models.get_image_path)),
            ],
        ),
    ]
