# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 13:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferienhausWeb', '0013_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='desc_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
